export const samplePosts = [
  {
    id: 1,
    title: "Exploring Next.js 14",
    description: "A beginner's guide to building apps with Next.js 14.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Web Development",
    tags: ["nextjs", "react", "webdev"],
    content:
      "<h1>Introduction to Next.js 14</h1><p>Learn the basics and advanced features.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 2,
    title: "Top 10 VSCode Extensions",
    description: "Must-have extensions for developers.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Tools",
    tags: ["vscode", "productivity"],
    content: "<h1>Boost Your Productivity</h1><p>Here are my top picks...</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 3,
    title: "Mastering TypeScript",
    description: "A complete TypeScript guide for beginners.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Programming",
    tags: ["typescript", "javascript"],
    content:
      "<h1>Understanding TypeScript</h1><p>Types, interfaces, and more.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 4,
    title: "Building a Blog with Tailwind CSS",
    description: "Styling your blog with Tailwind CSS easily.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "CSS",
    tags: ["tailwind", "css", "design"],
    content: "<h1>Design with Tailwind</h1><p>Speed up your CSS workflow.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 5,
    title: "React Hooks Explained",
    description: "Understand useState, useEffect, and custom hooks.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["react", "hooks"],
    content: "<h1>React Hooks</h1><p>Powerful features in React.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 6,
    title: "Deploying with Vercel",
    description: "Deploy your Next.js app effortlessly using Vercel.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["vercel", "deployment"],
    content: "<h1>Vercel Deployment</h1><p>Push and deploy instantly.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 7,
    title: "Best Backend Frameworks in 2025",
    description: "A comparison of the top backend frameworks.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Backend",
    tags: ["nodejs", "express", "nestjs"],
    content: "<h1>Backend Choices</h1><p>What suits your project?</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 8,
    title: "Understanding Prisma ORM",
    description: "Using Prisma to handle your database easily.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Database",
    tags: ["prisma", "database", "orm"],
    content:
      "<h1>Prisma ORM</h1><p>Simple and powerful database management.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 9,
    title: "Docker Basics for Beginners",
    description: "Containerize your apps easily with Docker.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["docker", "containers"],
    content:
      "<h1>Docker Introduction</h1><p>Build, ship, and run your apps.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 10,
    title: "Secure Authentication with NextAuth.js",
    description: "Add Google and GitHub OAuth quickly.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Authentication",
    tags: ["nextauth", "oauth", "security"],
    content: "<h1>NextAuth Guide</h1><p>Authentication made simple.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 11,
    title: "Learning GraphQL",
    description: "How GraphQL is different from REST.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "API",
    tags: ["graphql", "api"],
    content: "<h1>GraphQL Basics</h1><p>Efficient API development.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 12,
    title: "Building REST APIs with Express",
    description: "Quickstart guide for REST APIs.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Backend",
    tags: ["express", "nodejs", "restapi"],
    content: "<h1>Express REST API</h1><p>Building scalable backends.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 13,
    title: "MySQL vs PostgreSQL: Which to Choose?",
    description: "Choosing the right database for your project.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Database",
    tags: ["mysql", "postgresql", "database"],
    content: "<h1>Database Wars</h1><p>Pros and cons explained.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 14,
    title: "Introduction to Serverless Functions",
    description: "How to deploy serverless APIs.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Cloud",
    tags: ["serverless", "cloud"],
    content: "<h1>Serverless 101</h1><p>Scalable and cost-efficient.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 15,
    title: "SEO Tips for Developers",
    description: "Improve your site's visibility.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Marketing",
    tags: ["seo", "webdev"],
    content: "<h1>SEO Guide</h1><p>Get found online!</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 16,
    title: "Understanding CI/CD Pipelines",
    description: "Automate testing and deployment.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["cicd", "automation"],
    content: "<h1>CI/CD Introduction</h1><p>Faster development cycles.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 17,
    title: "How to Use Zustand for State Management",
    description: "Simple global state management with Zustand.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["zustand", "react", "state"],
    content: "<h1>Zustand Basics</h1><p>Minimalistic and scalable.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 18,
    title: "Understanding Tailwind's JIT Mode",
    description: "How JIT improves Tailwind performance.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "CSS",
    tags: ["tailwind", "jit"],
    content: "<h1>JIT Compilation</h1><p>Blazing fast builds.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 19,
    title: "The Basics of Web Accessibility (a11y)",
    description: "Making your apps accessible to everyone.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["a11y", "accessibility"],
    content: "<h1>Web Accessibility</h1><p>Inclusive design matters.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 20,
    title: "Writing Clean Code in JavaScript",
    description: "Tips and techniques for clean, readable code.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Programming",
    tags: ["javascript", "bestpractices"],
    content: "<h1>Clean Code</h1><p>Write better JavaScript.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 21,
    title: "Exploring Next.js 14",
    description: "A beginner's guide to building apps with Next.js 14.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Web Development",
    tags: ["nextjs", "react", "webdev"],
    content:
      "<h1>Introduction to Next.js 14</h1><p>Learn the basics and advanced features.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 22,
    title: "Top 10 VSCode Extensions",
    description: "Must-have extensions for developers.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Tools",
    tags: ["vscode", "productivity"],
    content: "<h1>Boost Your Productivity</h1><p>Here are my top picks...</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 23,
    title: "Mastering TypeScript",
    description: "A complete TypeScript guide for beginners.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Programming",
    tags: ["typescript", "javascript"],
    content:
      "<h1>Understanding TypeScript</h1><p>Types, interfaces, and more.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 24,
    title: "Building a Blog with Tailwind CSS",
    description: "Styling your blog with Tailwind CSS easily.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "CSS",
    tags: ["tailwind", "css", "design"],
    content: "<h1>Design with Tailwind</h1><p>Speed up your CSS workflow.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 25,
    title: "React Hooks Explained",
    description: "Understand useState, useEffect, and custom hooks.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["react", "hooks"],
    content: "<h1>React Hooks</h1><p>Powerful features in React.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 26,
    title: "Deploying with Vercel",
    description: "Deploy your Next.js app effortlessly using Vercel.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["vercel", "deployment"],
    content: "<h1>Vercel Deployment</h1><p>Push and deploy instantly.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 27,
    title: "Best Backend Frameworks in 2025",
    description: "A comparison of the top backend frameworks.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Backend",
    tags: ["nodejs", "express", "nestjs"],
    content: "<h1>Backend Choices</h1><p>What suits your project?</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 28,
    title: "Understanding Prisma ORM",
    description: "Using Prisma to handle your database easily.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Database",
    tags: ["prisma", "database", "orm"],
    content:
      "<h1>Prisma ORM</h1><p>Simple and powerful database management.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 29,
    title: "Docker Basics for Beginners",
    description: "Containerize your apps easily with Docker.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["docker", "containers"],
    content:
      "<h1>Docker Introduction</h1><p>Build, ship, and run your apps.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 30,
    title: "Secure Authentication with NextAuth.js",
    description: "Add Google and GitHub OAuth quickly.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Authentication",
    tags: ["nextauth", "oauth", "security"],
    content: "<h1>NextAuth Guide</h1><p>Authentication made simple.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 31,
    title: "Learning GraphQL",
    description: "How GraphQL is different from REST.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "API",
    tags: ["graphql", "api"],
    content: "<h1>GraphQL Basics</h1><p>Efficient API development.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 32,
    title: "Building REST APIs with Express",
    description: "Quickstart guide for REST APIs.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Backend",
    tags: ["express", "nodejs", "restapi"],
    content: "<h1>Express REST API</h1><p>Building scalable backends.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 33,
    title: "MySQL vs PostgreSQL: Which to Choose?",
    description: "Choosing the right database for your project.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Database",
    tags: ["mysql", "postgresql", "database"],
    content: "<h1>Database Wars</h1><p>Pros and cons explained.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 34,
    title: "Introduction to Serverless Functions",
    description: "How to deploy serverless APIs.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Cloud",
    tags: ["serverless", "cloud"],
    content: "<h1>Serverless 101</h1><p>Scalable and cost-efficient.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 35,
    title: "SEO Tips for Developers",
    description: "Improve your site's visibility.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Marketing",
    tags: ["seo", "webdev"],
    content: "<h1>SEO Guide</h1><p>Get found online!</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 36,
    title: "Understanding CI/CD Pipelines",
    description: "Automate testing and deployment.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "DevOps",
    tags: ["cicd", "automation"],
    content: "<h1>CI/CD Introduction</h1><p>Faster development cycles.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 37,
    title: "How to Use Zustand for State Management",
    description: "Simple global state management with Zustand.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["zustand", "react", "state"],
    content: "<h1>Zustand Basics</h1><p>Minimalistic and scalable.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
  {
    id: 38,
    title: "Understanding Tailwind's JIT Mode",
    description: "How JIT improves Tailwind performance.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "CSS",
    tags: ["tailwind", "jit"],
    content: "<h1>JIT Compilation</h1><p>Blazing fast builds.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 3,
  },
  {
    id: 39,
    title: "The Basics of Web Accessibility (a11y)",
    description: "Making your apps accessible to everyone.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Frontend",
    tags: ["a11y", "accessibility"],
    content: "<h1>Web Accessibility</h1><p>Inclusive design matters.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 2,
  },
  {
    id: 40,
    title: "Writing Clean Code in JavaScript",
    description: "Tips and techniques for clean, readable code.",
    image:
      "https://images.unsplash.com/photo-1620680779930-e74c15c8f7a0?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Programming",
    tags: ["javascript", "bestpractices"],
    content: "<h1>Clean Code</h1><p>Write better JavaScript.</p>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: 1,
  },
];
